# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dr. Edwin Lee, PhD
email: edwin dot lee at NREL dot gov
description: >- # this means to ignore newlines until "baseurl:"
  I am a practicing mechanical engineer who just happens to spend most
  of his time writing Python and C++ code.  I am interested in all things
  building simulation related, and focused on using the best tools for the job at hand.
baseurl: "/cv" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: myoldmopar
github_username: myoldmopar
linkedin_username: edwin-lee-b4207122

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
 - career.md
 - school.md
 - publications.md
 - coding.md
 - hobbies.md
